repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b969e2851312ca2b24bbec879ba4954341d1bd12  # v0.15.5
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [numpy, torch, Pillow]
        language_version: python3.12
