"""Provider-neutral components for the LS Trusted Cooperative Runtime."""

from .adapters import DAOlimConfig, DAOlimRoutingAdapter
from .contracts import (
    CognitiveTrail,
    DecisionCode,
    EvidenceDecision,
    ExecutionAuthorization,
    ReplayDecision,
    ReplayRecord,
    ReusableArtifact,
    RoleAssignment,
    RouteDecision,
    TaskEnvelope,
    TrailEvent,
    TrailEventType,
    WorkflowPlan,
    WorkflowStep,
)
from .orchestrator import (
    DeterministicWorkflowOrchestrator,
    OrchestrationDepthError,
    OrchestratorConfig,
)
from .protocols import (
    AuthorizationBundleAdapter,
    CausalAuditAdapter,
    EventStoreAdapter,
    EvidenceGateAdapter,
    ExecutionControlAdapter,
    ReplayAdapter,
    RoutingAdapter,
    WorkflowOrchestrator,
)
from .registry import (
    AdapterRegistration,
    AdapterRegistry,
    AdapterRegistryError,
    DuplicateAdapterError,
    UnknownAdapterError,
    UnsupportedCapabilityError,
)
from .routing import (
    BackendCandidate,
    DeterministicRoutingAdapter,
    MalformedRouteResponseError,
    NoRouteError,
    RoutingDisabledError,
    RoutingError,
    RoutingPolicy,
    RoutingTimeoutError,
    RoutingUnavailableError,
    route_decision_event,
)

__all__ = [
    "AdapterRegistration",
    "AdapterRegistry",
    "AdapterRegistryError",
    "AuthorizationBundleAdapter",
    "BackendCandidate",
    "CausalAuditAdapter",
    "CognitiveTrail",
    "DAOlimConfig",
    "DAOlimRoutingAdapter",
    "DecisionCode",
    "DeterministicRoutingAdapter",
    "DeterministicWorkflowOrchestrator",
    "DuplicateAdapterError",
    "EventStoreAdapter",
    "EvidenceDecision",
    "EvidenceGateAdapter",
    "ExecutionAuthorization",
    "ExecutionControlAdapter",
    "MalformedRouteResponseError",
    "NoRouteError",
    "OrchestrationDepthError",
    "OrchestratorConfig",
    "ReplayAdapter",
    "ReplayDecision",
    "ReplayRecord",
    "ReusableArtifact",
    "RoleAssignment",
    "RouteDecision",
    "RoutingAdapter",
    "RoutingDisabledError",
    "RoutingError",
    "RoutingPolicy",
    "RoutingTimeoutError",
    "RoutingUnavailableError",
    "TaskEnvelope",
    "TrailEvent",
    "TrailEventType",
    "UnknownAdapterError",
    "UnsupportedCapabilityError",
    "WorkflowOrchestrator",
    "WorkflowPlan",
    "WorkflowStep",
    "route_decision_event",
]
