from __future__ import annotations

from datetime import datetime, timezone

from ls.agent_shell.runtime.approval_manager import ApprovalManager
from ls.agent_shell.runtime.artifact_manager import ArtifactManager
from ls.agent_shell.runtime.trace_store import TraceStore
from ls.agent_shell.schemas.step import Step
from ls.agent_shell.storage.sqlite_store import SQLiteStore, from_json, to_json


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


class Executor:
    MUTATING_STEP_TYPES = {"write", "git", "browser", "tool", "artifact"}

    def __init__(
        self,
        store: SQLiteStore,
        approval_manager: ApprovalManager,
        artifact_manager: ArtifactManager,
        trace: TraceStore,
    ):
        self.store = store
        self.approval_manager = approval_manager
        self.artifact_manager = artifact_manager
        self.trace = trace

    def run(self, task_id: str, mode: str) -> None:
        steps = self.store.fetch_all("SELECT * FROM steps WHERE task_id=:task_id ORDER BY id ASC", task_id=task_id)
        self.store.update("tasks", "id", task_id, status="running", updated_at=utc_now())
        for row in steps:
            if row["status"] != "pending":
                continue
            step = Step(
                id=row["id"],
                task_id=row["task_id"],
                title=row["title"],
                description=row["description"],
                type=row["type"],
                reason=row["reason"],
                status=row["status"],
                needs_approval=bool(row["needs_approval"]),
                inputs=from_json(row["inputs_json"]),
                outputs=from_json(row["outputs_json"]),
            )
            if mode == "read-only" and step.type in self.MUTATING_STEP_TYPES:
                self.store.update("steps", "id", step.id, status="failed", ended_at=utc_now())
                self.store.update(
                    "tasks",
                    "id",
                    task_id,
                    status="failed",
                    summary=f"Read-only policy violation on step {step.id} ({step.type}).",
                    updated_at=utc_now(),
                )
                self.trace.log(
                    task_id,
                    f"Execution stopped: read-only mode forbids step type '{step.type}'.",
                    level="error",
                    step_id=step.id,
                )
                return
            already_approved = step.outputs.get("approval") == "granted"
            if self.approval_manager.requires_approval(step, mode) and not already_approved:
                approval = self.approval_manager.request(task_id, step)
                self.store.update("steps", "id", step.id, status="waiting_approval")
                self.store.update("tasks", "id", task_id, status="waiting_approval", updated_at=utc_now())
                self.trace.log(task_id, f"Paused on approval {approval.id} for {step.id}.", step_id=step.id)
                return
            self._execute_step(step)

        self.store.update(
            "tasks",
            "id",
            task_id,
            status="completed",
            summary="Task completed successfully.",
            updated_at=utc_now(),
        )
        self.trace.log(task_id, "Task completed with all planned steps executed.")

    def _execute_step(self, step: Step) -> None:
        self.store.update("steps", "id", step.id, status="running", started_at=utc_now())
        self.trace.log(step.task_id, f"Running {step.id}: {step.title}", step_id=step.id)

        outputs = {"result": f"Completed: {step.title}"}
        if step.type == "artifact":
            artifact = self.artifact_manager.create_text_artifact(
                task_id=step.task_id,
                title="Task report",
                rel_name="report.md",
                content=f"# {step.title}\n\nGenerated by LS Agent Shell MVP executor.",
            )
            outputs["artifact_id"] = artifact.id
            self.trace.log(step.task_id, f"Artifact created at {artifact.path_or_url}", step_id=step.id)

        self.store.update(
            "steps",
            "id",
            step.id,
            status="completed",
            outputs_json=to_json(outputs),
            ended_at=utc_now(),
        )
        self.trace.log(step.task_id, f"Completed {step.id}", step_id=step.id)

    def resume_after_approval(self, task_id: str, step_id: str) -> None:
        self.store.update(
            "steps",
            "id",
            step_id,
            status="pending",
            outputs_json=to_json({"approval": "granted"}),
        )
        self.trace.log(task_id, f"Approval granted for {step_id}; step returned to pending queue.", step_id=step_id)
