from __future__ import annotations

from typing import Any, Protocol


class TaskRuntime(Protocol):
    def plan_task(self, *, prompt: str, mode: str) -> dict[str, Any]: ...

    def run_task(self, *, prompt: str, mode: str) -> dict[str, Any]: ...

    def resume_task(self, *, task_id: str) -> dict[str, Any]: ...

    def get_status(self, *, task_id: str) -> dict[str, Any]: ...

    def get_trace(self, *, task_id: str, limit: int = 100) -> dict[str, Any]: ...

    def list_artifacts(self, *, task_id: str) -> dict[str, Any]: ...

    def approve(self, *, task_id: str, step_id: str) -> dict[str, Any]: ...

    def reject(self, *, task_id: str, step_id: str, reason: str) -> dict[str, Any]: ...
