#!/usr/bin/env python3
"""Render a reviewer-facing grant evidence summary.

The script consumes machine-readable outputs produced by `make grant-evidence`
and writes a compact Markdown report that a grant reviewer can inspect without
re-running every command manually.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


class GrantEvidenceError(ValueError):
    """Raised when expected grant evidence files are missing or malformed."""


def load_json(path: Path) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as file:
            payload = json.load(file)
    except FileNotFoundError as exc:
        raise GrantEvidenceError(f"Missing evidence file: {path}") from exc
    except json.JSONDecodeError as exc:
        raise GrantEvidenceError(f"Invalid JSON in {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise GrantEvidenceError(f"Expected JSON object in {path}")
    return payload


def load_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8").strip()
    except FileNotFoundError as exc:
        raise GrantEvidenceError(f"Missing evidence file: {path}") from exc


def bool_text(value: Any) -> str:
    return "yes" if bool(value) else "no"


def render_summary(input_dir: Path) -> str:
    demo = load_json(input_dir / "pcg_demo_output.json")
    red_team = load_json(input_dir / "pcg_red_team_block_output.json")
    evaluation = load_json(input_dir / "pcg_evaluation_report.json")
    tests = load_text(input_dir / "pcg_governance_tests.txt")

    accepted_nodes = demo.get("accepted_nodes") or []
    rows = evaluation.get("rows") or []
    limitations = evaluation.get("limitations") or []

    lines: list[str] = []
    lines.append("# LS Grant Evidence Summary")
    lines.append("")
    lines.append("This report is generated by `make grant-evidence` from checked-in LS Personal Cognitive Garden artifacts.")
    lines.append("")
    lines.append("## Claim under review")
    lines.append("")
    lines.append("> LS turns AI-assisted sessions into evidence-backed, human-reviewed, human-owned development state without allowing unauthorized profiling or employer surveillance.")
    lines.append("")
    lines.append("## Reproducibility entrypoint")
    lines.append("")
    lines.append("```bash")
    lines.append("make grant-evidence")
    lines.append("```")
    lines.append("")
    lines.append("## 1. Personal Cognitive Garden demo")
    lines.append("")
    lines.append(f"- Session: `{demo.get('session_id', 'unknown')}`")
    lines.append(f"- Session type: `{demo.get('session_type', 'unknown')}`")
    lines.append(f"- Development class: `{demo.get('development_class', 'unknown')}`")
    lines.append(f"- Developmental: **{bool_text(demo.get('is_developmental'))}**")
    lines.append(f"- Proposed status: `{demo.get('proposed_status', 'unknown')}`")
    lines.append(f"- Human review decision: `{demo.get('review_decision', 'unknown')}`")
    lines.append(f"- Reviewed by: `{demo.get('reviewed_by', 'unknown')}`")
    lines.append(f"- Accepted graph nodes: {', '.join(f'`{node}`' for node in accepted_nodes) if accepted_nodes else '`none`'}")
    lines.append("")
    lines.append("## 2. Anti-surveillance red-team result")
    lines.append("")
    lines.append(f"- Scenario: `{red_team.get('scenario_id', 'unknown')}`")
    lines.append(f"- Requester type: `{red_team.get('requester_type', 'unknown')}`")
    lines.append(f"- Decision: **{red_team.get('decision', 'unknown')}**")
    lines.append(f"- Reason: `{red_team.get('reason', 'unknown')}`")
    lines.append(f"- External action allowed: **{bool_text(red_team.get('external_action_allowed'))}**")
    blocked = red_team.get("blocked_requested_fields") or []
    lines.append(f"- Blocked requested fields: {', '.join(f'`{field}`' for field in blocked) if blocked else '`none`'}")
    lines.append(f"- Safe alternative: {red_team.get('safe_alternative', 'unknown')}")
    lines.append("")
    lines.append("## 3. Synthetic evaluation harness")
    lines.append("")
    lines.append(f"- Total sessions: **{evaluation.get('total', 0)}**")
    lines.append(f"- Class accuracy: **{evaluation.get('class_accuracy', 'unknown')}**")
    lines.append(f"- Developmental accuracy: **{evaluation.get('developmental_accuracy', 'unknown')}**")
    lines.append("")
    lines.append("| Session | Expected class | Predicted class | Developmental match |")
    lines.append("|---|---|---|---|")
    for row in rows:
        lines.append(
            "| "
            f"`{row.get('session_id', 'unknown')}` | "
            f"`{row.get('expected_class', 'unknown')}` | "
            f"`{row.get('predicted_class', 'unknown')}` | "
            f"{bool_text(row.get('developmental_match'))} |"
        )
    lines.append("")
    lines.append("## 4. Governance tests")
    lines.append("")
    lines.append("```text")
    lines.append(tests or "no test output captured")
    lines.append("```")
    lines.append("")
    lines.append("## Limitations")
    lines.append("")
    if limitations:
        for item in limitations:
            lines.append(f"- {item}")
    else:
        lines.append("- No limitations were reported by the evaluation harness.")
    lines.append("- This evidence bundle demonstrates reproducibility and governance boundaries, not production-grade classification or long-term learning outcomes.")
    lines.append("")
    lines.append("## Next evidence milestones")
    lines.append("")
    lines.append("1. Expand anti-surveillance red-team scenarios beyond the initial employer request.")
    lines.append("2. Replace synthetic labels with 5-10 consented human-reviewed AI sessions.")
    lines.append("3. Add a privacy and consent architecture note with export receipts.")
    lines.append("4. Publish a short technical report describing methods, failure modes, and evaluation results.")
    lines.append("")
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render LS grant evidence summary Markdown.")
    parser.add_argument("--input-dir", type=Path, required=True, help="Directory containing grant evidence JSON/text outputs.")
    parser.add_argument("--output", type=Path, required=True, help="Markdown file to write.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        summary = render_summary(args.input_dir.resolve())
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(summary + "\n", encoding="utf-8")
    except GrantEvidenceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
