#!/usr/bin/env bash
set -euo pipefail

: "${TARGET_ENV_FILE:?TARGET_ENV_FILE is required}"
: "${OUTPUT_DIR:?OUTPUT_DIR is required}"
: "${CAUSAL_PROMPT_FILE:?CAUSAL_PROMPT_FILE is required}"

# This file is generated by tools/causal_review_request.py from wrapper-owned,
# validated fields only. It is shell-quoted and covered by injection tests.
source "$TARGET_ENV_FILE"
mkdir -p "$OUTPUT_DIR"

run_grok() {
  export REVIEW_JSON_FILE="$OUTPUT_DIR/grok-review.json"
  export REVIEW_MD_FILE="$OUTPUT_DIR/grok-review.md"
  export RAW_RESPONSE_FILE="$OUTPUT_DIR/grok-response.raw.txt"

  # Emergency cost kill switch: Grok is disabled by default even when the
  # repository secret still exists. Re-enabling requires an explicit trusted
  # workflow opt-in with GROK_ENABLED=true.
  if [[ "${GROK_ENABLED:-false}" == "true" && -n "${XAI_API_KEY:-}" ]]; then
    python tools/grok_causal_review.py review || true
  else
    : > "$RAW_RESPONSE_FILE"
    python tools/grok_causal_review.py diagnostic \
      --status NOT_RUN \
      --provenance UNVERIFIED \
      --details "Grok is disabled by repository policy. No xAI model call was made."
  fi
  if [[ ! -s "$REVIEW_JSON_FILE" ]]; then
    : > "$RAW_RESPONSE_FILE"
    python tools/grok_causal_review.py diagnostic \
      --status FAILED \
      --provenance UNVERIFIED \
      --details "Grok runner ended without a validated artifact."
  fi
}

run_deepseek() {
  export DEEPSEEK_LANE_FILE="$OUTPUT_DIR/deepseek-lane.json"
  export REVIEW_JSON_FILE="$OUTPUT_DIR/deepseek-review.json"
  export REVIEW_MD_FILE="$OUTPUT_DIR/deepseek-review.md"
  export RAW_RESPONSE_FILE="$OUTPUT_DIR/deepseek-response.raw.txt"
  if [[ -n "${DEEPSEEK_API_KEY:-}" ]]; then
    python tools/deepseek_causal_review.py review || true
  else
    : > "$RAW_RESPONSE_FILE"
    python tools/deepseek_causal_review.py diagnostic \
      --status NOT_RUN \
      --provenance UNVERIFIED \
      --details "Repository secret DEEPSEEK_API_KEY is unavailable. No DeepSeek model call was made."
  fi
  if [[ ! -s "$REVIEW_JSON_FILE" || ! -s "$DEEPSEEK_LANE_FILE" ]]; then
    : > "$RAW_RESPONSE_FILE"
    python tools/deepseek_causal_review.py diagnostic \
      --status FAILED \
      --provenance UNVERIFIED \
      --details "DeepSeek runner ended without a validated artifact."
  fi
}

run_codex() {
  export REVIEW_JSON_FILE="$OUTPUT_DIR/codex-review.json"
  export REVIEW_MD_FILE="$OUTPUT_DIR/codex-review.md"
  export RAW_RESPONSE_FILE="$OUTPUT_DIR/codex-response.raw.json"
  if [[ -n "${OPENAI_API_KEY:-}" ]]; then
    python tools/codex_causal_review.py review || true
  else
    : > "$RAW_RESPONSE_FILE"
    python tools/codex_causal_review.py diagnostic \
      --status NOT_RUN \
      --provenance UNVERIFIED \
      --details "Repository secret OPENAI_API_KEY is unavailable. No Codex model call was made."
  fi
  if [[ ! -s "$REVIEW_JSON_FILE" ]]; then
    : > "$RAW_RESPONSE_FILE"
    python tools/codex_causal_review.py diagnostic \
      --status FAILED \
      --provenance UNVERIFIED \
      --details "Codex runner ended without a validated artifact."
  fi
}

# Reviewers run blind. None receives another reviewer's artifact as input.
run_grok
run_deepseek
run_codex
